# Generated by Django 5.2.1 on 2025-07-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', 'add_notification_field'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            PRAGMA foreign_keys=off;
            
            CREATE TABLE IF NOT EXISTS products_notification_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                message TEXT NOT NULL,
                is_read BOOL NOT NULL,
                created_at DATETIME NOT NULL,
                user_id INTEGER NOT NULL REFERENCES auth_user(id)
            );
            
            INSERT INTO products_notification_new (id, message, is_read, created_at, user_id)
            SELECT id, message, is_read, created_at, user_id
            FROM products_notification;
            
            DROP TABLE products_notification;
            
            ALTER TABLE products_notification_new RENAME TO products_notification;
            
            PRAGMA foreign_keys=on;
            """,
            reverse_sql="""
            -- No reverse operation needed
            """
        ),
    ]
